//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionPlan
    {
        public int Id { get; set; }
        public int IdPlan { get; set; }
        public int IdCollection { get; set; }
    
        public virtual Collection Collection { get; set; }
    }
}
