//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TerrazasEntities : DbContext
    {
        public TerrazasEntities()
            : base("name=TerrazasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<Charge> Charge { get; set; }
        public virtual DbSet<Collection> Collection { get; set; }
        public virtual DbSet<HouseState> HouseState { get; set; }
        public virtual DbSet<Incident> Incident { get; set; }
        public virtual DbSet<IncidentState> IncidentState { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<InformationType> InformationType { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<Resident> Resident { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<SocialArea> SocialArea { get; set; }
        public virtual DbSet<User> User { get; set; }

        public System.Data.Entity.DbSet<Infraestructure.Model.ViewModel.Account.ViewModelAccount> ViewModelAccounts { get; set; }
    }
}
